version: "3.8"
services:
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: -js

  postgres-user:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: userdb

  postgres-product:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: productdb

  postgres-order:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: orderdb

  postgres-notification:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: notificationdb

  postgres-analytics:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: analyticsdb

  user-service:
    build: ./services/user-service
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:root@postgres-user:5432/userdb

  product-service:
    build: ./services/product-service
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:root@postgres-product:5432/productdb

  order-service:
    build: ./services/order-service
    ports:
      - "3003:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:root@postgres-order:5432/orderdb

  notification-service:
    build: ./services/notification-service
    ports:
      - "3004:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:root@postgres-notification:5432/notificationdb

  analytics-service:
    build: ./services/analytics-service
    ports:
      - "3005:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:root@postgres-analytics:5432/analyticsdb
